'use strict';var aa;function ba(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var ca=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function da(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var ea=da(this);function l(a,b){if(b)a:{var c=ea;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&ca(c,a,{configurable:!0,writable:!0,value:b})}}
l("Symbol",function(a){function b(f){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(f||"")+"_"+e++,f)}function c(f,g){this.g=f;ca(this,"description",{configurable:!0,writable:!0,value:g})}if(a)return a;c.prototype.toString=function(){return this.g};var d="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",e=0;return b});
l("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=ea[b[c]];typeof d==="function"&&typeof d.prototype[a]!="function"&&ca(d.prototype,a,{configurable:!0,writable:!0,value:function(){return fa(ba(this))}})}return a});function fa(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
var ha=typeof Object.create=="function"?Object.create:function(a){function b(){}b.prototype=a;return new b},ia;if(typeof Object.setPrototypeOf=="function")ia=Object.setPrototypeOf;else{var ja;a:{var ka={a:!0},la={};try{la.__proto__=ka;ja=la.a;break a}catch(a){}ja=!1}ia=ja?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ma=ia;
function p(a,b){a.prototype=ha(b.prototype);a.prototype.constructor=a;if(ma)ma(a,b);else for(var c in b)if(c!="prototype")if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.ea=b.prototype}function q(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:ba(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}
function na(){this.o=!1;this.l=null;this.h=void 0;this.g=1;this.v=this.i=0;this.m=null}function oa(a){if(a.o)throw new TypeError("Generator is already running");a.o=!0}na.prototype.u=function(a){this.h=a};function pa(a,b){a.m={W:b,isException:!0};a.g=a.i||a.v}na.prototype.return=function(a){this.m={return:a};this.g=this.v};function r(a,b,c){a.g=c;return{value:b}}function qa(a,b){a.g=b;a.i=0}function ra(a){a.i=0;var b=a.m.W;a.m=null;return b}function sa(a){this.g=new na;this.h=a}
function ta(a,b){oa(a.g);var c=a.g.l;if(c)return ua(a,"return"in c?c["return"]:function(d){return{value:d,done:!0}},b,a.g.return);a.g.return(b);return va(a)}function ua(a,b,c,d){try{var e=b.call(a.g.l,c);if(!(e instanceof Object))throw new TypeError("Iterator result "+e+" is not an object");if(!e.done)return a.g.o=!1,e;var f=e.value}catch(g){return a.g.l=null,pa(a.g,g),va(a)}a.g.l=null;d.call(a.g,f);return va(a)}
function va(a){for(;a.g.g;)try{var b=a.h(a.g);if(b)return a.g.o=!1,{value:b.value,done:!1}}catch(c){a.g.h=void 0,pa(a.g,c)}a.g.o=!1;if(a.g.m){b=a.g.m;a.g.m=null;if(b.isException)throw b.W;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function wa(a){this.next=function(b){oa(a.g);a.g.l?b=ua(a,a.g.l.next,b,a.g.u):(a.g.u(b),b=va(a));return b};this.throw=function(b){oa(a.g);a.g.l?b=ua(a,a.g.l["throw"],b,a.g.u):(pa(a.g,b),b=va(a));return b};this.return=function(b){return ta(a,b)};this[Symbol.iterator]=function(){return this}}function xa(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}return new Promise(function(d,e){function f(g){g.done?d(g.value):Promise.resolve(g.value).then(b,c).then(f,e)}f(a.next())})}
function t(a){return xa(new wa(new sa(a)))}l("Reflect.setPrototypeOf",function(a){return a?a:ma?function(b,c){try{return ma(b,c),!0}catch(d){return!1}}:null});
l("Promise",function(a){function b(g){this.h=0;this.i=void 0;this.g=[];this.u=!1;var h=this.l();try{g(h.resolve,h.reject)}catch(k){h.reject(k)}}function c(){this.g=null}function d(g){return g instanceof b?g:new b(function(h){h(g)})}if(a)return a;c.prototype.h=function(g){if(this.g==null){this.g=[];var h=this;this.i(function(){h.m()})}this.g.push(g)};var e=ea.setTimeout;c.prototype.i=function(g){e(g,0)};c.prototype.m=function(){for(;this.g&&this.g.length;){var g=this.g;this.g=[];for(var h=0;h<g.length;++h){var k=
g[h];g[h]=null;try{k()}catch(m){this.l(m)}}}this.g=null};c.prototype.l=function(g){this.i(function(){throw g;})};b.prototype.l=function(){function g(m){return function(n){k||(k=!0,m.call(h,n))}}var h=this,k=!1;return{resolve:g(this.C),reject:g(this.m)}};b.prototype.C=function(g){if(g===this)this.m(new TypeError("A Promise cannot resolve to itself"));else if(g instanceof b)this.G(g);else{a:switch(typeof g){case "object":var h=g!=null;break a;case "function":h=!0;break a;default:h=!1}h?this.B(g):this.o(g)}};
b.prototype.B=function(g){var h=void 0;try{h=g.then}catch(k){this.m(k);return}typeof h=="function"?this.H(h,g):this.o(g)};b.prototype.m=function(g){this.v(2,g)};b.prototype.o=function(g){this.v(1,g)};b.prototype.v=function(g,h){if(this.h!=0)throw Error("Cannot settle("+g+", "+h+"): Promise already settled in state"+this.h);this.h=g;this.i=h;this.h===2&&this.F();this.D()};b.prototype.F=function(){var g=this;e(function(){if(g.A()){var h=ea.console;typeof h!=="undefined"&&h.error(g.i)}},1)};b.prototype.A=
function(){if(this.u)return!1;var g=ea.CustomEvent,h=ea.Event,k=ea.dispatchEvent;if(typeof k==="undefined")return!0;typeof g==="function"?g=new g("unhandledrejection",{cancelable:!0}):typeof h==="function"?g=new h("unhandledrejection",{cancelable:!0}):(g=ea.document.createEvent("CustomEvent"),g.initCustomEvent("unhandledrejection",!1,!0,g));g.promise=this;g.reason=this.i;return k(g)};b.prototype.D=function(){if(this.g!=null){for(var g=0;g<this.g.length;++g)f.h(this.g[g]);this.g=null}};var f=new c;
b.prototype.G=function(g){var h=this.l();g.K(h.resolve,h.reject)};b.prototype.H=function(g,h){var k=this.l();try{g.call(h,k.resolve,k.reject)}catch(m){k.reject(m)}};b.prototype.then=function(g,h){function k(x,z){return typeof x=="function"?function(G){try{m(x(G))}catch(C){n(C)}}:z}var m,n,w=new b(function(x,z){m=x;n=z});this.K(k(g,m),k(h,n));return w};b.prototype.catch=function(g){return this.then(void 0,g)};b.prototype.K=function(g,h){function k(){switch(m.h){case 1:g(m.i);break;case 2:h(m.i);break;
default:throw Error("Unexpected state: "+m.h);}}var m=this;this.g==null?f.h(k):this.g.push(k);this.u=!0};b.resolve=d;b.reject=function(g){return new b(function(h,k){k(g)})};b.race=function(g){return new b(function(h,k){for(var m=q(g),n=m.next();!n.done;n=m.next())d(n.value).K(h,k)})};b.all=function(g){var h=q(g),k=h.next();return k.done?d([]):new b(function(m,n){function w(G){return function(C){x[G]=C;z--;z==0&&m(x)}}var x=[],z=0;do x.push(void 0),z++,d(k.value).K(w(x.length-1),n),k=h.next();while(!k.done)})};
return b});l("Object.setPrototypeOf",function(a){return a||ma});function u(a,b){return Object.prototype.hasOwnProperty.call(a,b)}var ya=typeof Object.assign=="function"?Object.assign:function(a,b){if(a==null)throw new TypeError("No nullish arg");a=Object(a);for(var c=1;c<arguments.length;c++){var d=arguments[c];if(d)for(var e in d)u(d,e)&&(a[e]=d[e])}return a};l("Object.assign",function(a){return a||ya});
l("WeakMap",function(a){function b(k){this.g=(h+=Math.random()+1).toString();if(k){k=q(k);for(var m;!(m=k.next()).done;)m=m.value,this.set(m[0],m[1])}}function c(){}function d(k){var m=typeof k;return m==="object"&&k!==null||m==="function"}function e(k){if(!u(k,g)){var m=new c;ca(k,g,{value:m})}}function f(k){var m=Object[k];m&&(Object[k]=function(n){if(n instanceof c)return n;Object.isExtensible(n)&&e(n);return m(n)})}if(function(){if(!a||!Object.seal)return!1;try{var k=Object.seal({}),m=Object.seal({}),
n=new a([[k,2],[m,3]]);if(n.get(k)!=2||n.get(m)!=3)return!1;n.delete(k);n.set(m,4);return!n.has(k)&&n.get(m)==4}catch(w){return!1}}())return a;var g="$jscomp_hidden_"+Math.random();f("freeze");f("preventExtensions");f("seal");var h=0;b.prototype.set=function(k,m){if(!d(k))throw Error("Invalid WeakMap key");e(k);if(!u(k,g))throw Error("WeakMap key fail: "+k);k[g][this.g]=m;return this};b.prototype.get=function(k){return d(k)&&u(k,g)?k[g][this.g]:void 0};b.prototype.has=function(k){return d(k)&&u(k,
g)&&u(k[g],this.g)};b.prototype.delete=function(k){return d(k)&&u(k,g)&&u(k[g],this.g)?delete k[g][this.g]:!1};return b});
l("Map",function(a){function b(){var h={};return h.previous=h.next=h.head=h}function c(h,k){var m=h[1];return fa(function(){if(m){for(;m.head!=h[1];)m=m.previous;for(;m.next!=m.head;)return m=m.next,{done:!1,value:k(m)};m=null}return{done:!0,value:void 0}})}function d(h,k){var m=k&&typeof k;m=="object"||m=="function"?f.has(k)?m=f.get(k):(m=""+ ++g,f.set(k,m)):m="p_"+k;var n=h[0][m];if(n&&u(h[0],m))for(h=0;h<n.length;h++){var w=n[h];if(k!==k&&w.key!==w.key||k===w.key)return{id:m,list:n,index:h,entry:w}}return{id:m,
list:n,index:-1,entry:void 0}}function e(h){this[0]={};this[1]=b();this.size=0;if(h){h=q(h);for(var k;!(k=h.next()).done;)k=k.value,this.set(k[0],k[1])}}if(function(){if(!a||typeof a!="function"||!a.prototype.entries||typeof Object.seal!="function")return!1;try{var h=Object.seal({x:4}),k=new a(q([[h,"s"]]));if(k.get(h)!="s"||k.size!=1||k.get({x:4})||k.set({x:4},"t")!=k||k.size!=2)return!1;var m=k.entries(),n=m.next();if(n.done||n.value[0]!=h||n.value[1]!="s")return!1;n=m.next();return n.done||n.value[0].x!=
4||n.value[1]!="t"||!m.next().done?!1:!0}catch(w){return!1}}())return a;var f=new WeakMap;e.prototype.set=function(h,k){h=h===0?0:h;var m=d(this,h);m.list||(m.list=this[0][m.id]=[]);m.entry?m.entry.value=k:(m.entry={next:this[1],previous:this[1].previous,head:this[1],key:h,value:k},m.list.push(m.entry),this[1].previous.next=m.entry,this[1].previous=m.entry,this.size++);return this};e.prototype.delete=function(h){h=d(this,h);return h.entry&&h.list?(h.list.splice(h.index,1),h.list.length||delete this[0][h.id],
h.entry.previous.next=h.entry.next,h.entry.next.previous=h.entry.previous,h.entry.head=null,this.size--,!0):!1};e.prototype.clear=function(){this[0]={};this[1]=this[1].previous=b();this.size=0};e.prototype.has=function(h){return!!d(this,h).entry};e.prototype.get=function(h){return(h=d(this,h).entry)&&h.value};e.prototype.entries=function(){return c(this,function(h){return[h.key,h.value]})};e.prototype.keys=function(){return c(this,function(h){return h.key})};e.prototype.values=function(){return c(this,
function(h){return h.value})};e.prototype.forEach=function(h,k){for(var m=this.entries(),n;!(n=m.next()).done;)n=n.value,h.call(k,n[1],n[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var g=0;return e});
l("Array.from",function(a){return a?a:function(b,c,d){c=c!=null?c:function(h){return h};var e=[],f=typeof Symbol!="undefined"&&Symbol.iterator&&b[Symbol.iterator];if(typeof f=="function"){b=f.call(b);for(var g=0;!(f=b.next()).done;)e.push(c.call(d,f.value,g++))}else for(f=b.length,g=0;g<f;g++)e.push(c.call(d,b[g],g));return e}});l("Object.entries",function(a){return a?a:function(b){var c=[],d;for(d in b)u(b,d)&&c.push([d,b[d]]);return c}});
l("Number.isFinite",function(a){return a?a:function(b){return typeof b!=="number"?!1:!isNaN(b)&&b!==Infinity&&b!==-Infinity}});l("Number.MAX_SAFE_INTEGER",function(){return 9007199254740991});l("Number.MIN_SAFE_INTEGER",function(){return-9007199254740991});l("Number.isInteger",function(a){return a?a:function(b){return Number.isFinite(b)?b===Math.floor(b):!1}});l("Number.isSafeInteger",function(a){return a?a:function(b){return Number.isInteger(b)&&Math.abs(b)<=Number.MAX_SAFE_INTEGER}});
l("Object.is",function(a){return a?a:function(b,c){return b===c?b!==0||1/b===1/c:b!==b&&c!==c}});l("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(c<0&&(c=Math.max(c+e,0));c<e;c++){var f=d[c];if(f===b||Object.is(f,b))return!0}return!1}});
l("String.prototype.includes",function(a){return a?a:function(b,c){if(this==null)throw new TypeError("The 'this' value for String.prototype.includes must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.includes must not be a regular expression");return this.indexOf(b,c||0)!==-1}});
function za(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e}l("Array.prototype.entries",function(a){return a?a:function(){return za(this,function(b,c){return[b,c]})}});l("Math.trunc",function(a){return a?a:function(b){b=Number(b);if(isNaN(b)||b===Infinity||b===-Infinity||b===0)return b;var c=Math.floor(Math.abs(b));return b<0?-c:c}});
l("Array.prototype.find",function(a){return a?a:function(b,c){a:{var d=this;d instanceof String&&(d=String(d));for(var e=d.length,f=0;f<e;f++){var g=d[f];if(b.call(c,g,f,d)){b=g;break a}}b=void 0}return b}});l("Number.isNaN",function(a){return a?a:function(b){return typeof b==="number"&&isNaN(b)}});/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var Aa=this||self;function Ba(a,b){a:{var c=["CLOSURE_FLAGS"];for(var d=Aa,e=0;e<c.length;e++)if(d=d[c[e]],d==null){c=null;break a}c=d}a=c&&c[a];return a!=null?a:b}function Ca(a){return a};var Da=Ba(610401301,!1),Ea=Ba(748402147,Ba(1,!0));function Fa(){return typeof BigInt==="function"};var Ga=typeof Aa.BigInt==="function"&&typeof Aa.BigInt(0)==="bigint";var Ha=Number.MIN_SAFE_INTEGER.toString(),Ia=Ga?BigInt(Number.MIN_SAFE_INTEGER):void 0,Ja=Number.MAX_SAFE_INTEGER.toString(),Ka=Ga?BigInt(Number.MAX_SAFE_INTEGER):void 0;function La(a,b){if(a.length>b.length)return!1;if(a.length<b.length||a===b)return!0;for(var c=0;c<a.length;c++){var d=a[c],e=b[c];if(d>e)return!1;if(d<e)return!0}};var Ma=typeof Uint8Array.prototype.slice==="function",v=0,y=0,Na;function Oa(a){var b=a>>>0;v=b;y=(a-b)/4294967296>>>0}function Pa(a){if(a<0){Oa(-a);var b=q(Qa(v,y));a=b.next().value;b=b.next().value;v=a>>>0;y=b>>>0}else Oa(a)}function Ra(a){var b=Na||(Na=new DataView(new ArrayBuffer(8)));b.setFloat32(0,+a,!0);y=0;v=b.getUint32(0,!0)}function Sa(a){var b=Na||(Na=new DataView(new ArrayBuffer(8)));b.setFloat64(0,+a,!0);v=b.getUint32(0,!0);y=b.getUint32(4,!0)}
function Ta(a,b){var c=b*4294967296+(a>>>0);return Number.isSafeInteger(c)?c:Ua(a,b)}function Va(a,b){var c=b&2147483648;c&&(a=~a+1>>>0,b=~b>>>0,a==0&&(b=b+1>>>0));a=Ta(a,b);return typeof a==="number"?c?-a:a:c?"-"+a:a}
function Ua(a,b){b>>>=0;a>>>=0;if(b<=2097151)var c=""+(4294967296*b+a);else Fa()?c=""+(BigInt(b)<<BigInt(32)|BigInt(a)):(c=(a>>>24|b<<8)&16777215,b=b>>16&65535,a=(a&16777215)+c*6777216+b*6710656,c+=b*8147497,b*=2,a>=1E7&&(c+=a/1E7>>>0,a%=1E7),c>=1E7&&(b+=c/1E7>>>0,c%=1E7),c=b+Wa(c)+Wa(a));return c}function Wa(a){a=String(a);return"0000000".slice(a.length)+a}
function Xa(a){if(a.length<16)Pa(Number(a));else if(Fa())a=BigInt(a),v=Number(a&BigInt(4294967295))>>>0,y=Number(a>>BigInt(32)&BigInt(4294967295));else{var b=+(a[0]==="-");y=v=0;for(var c=a.length,d=b,e=(c-b)%6+b;e<=c;d=e,e+=6)d=Number(a.slice(d,e)),y*=1E6,v=v*1E6+d,v>=4294967296&&(y+=Math.trunc(v/4294967296),y>>>=0,v>>>=0);b&&(b=q(Qa(v,y)),a=b.next().value,b=b.next().value,v=a,y=b)}}function Qa(a,b){b=~b;a?a=~a+1:b+=1;return[a,b]};function Ya(a,b){this.h=a>>>0;this.g=b>>>0}function Za(a){return a.h===0?new Ya(0,1+~a.g):new Ya(~a.h+1,~a.g)}function $a(a){a=BigInt.asUintN(64,a);return new Ya(Number(a&BigInt(4294967295)),Number(a>>BigInt(32)))}function ab(a){if(!a)return bb||(bb=new Ya(0,0));if(!/^\d+$/.test(a))return null;Xa(a);return new Ya(v,y)}var bb;function cb(a,b){this.h=a>>>0;this.g=b>>>0}function db(a){a=BigInt.asUintN(64,a);return new cb(Number(a&BigInt(4294967295)),Number(a>>BigInt(32)))}
function eb(a){if(!a)return fb||(fb=new cb(0,0));if(!/^-?\d+$/.test(a))return null;Xa(a);return new cb(v,y)}var fb;function gb(){throw Error("Invalid UTF8");}function hb(a,b){b=String.fromCharCode.apply(null,b);return a==null?b:a+b}var ib=void 0,jb,kb=typeof TextDecoder!=="undefined",lb,mb=typeof String.prototype.isWellFormed==="function",nb=typeof TextEncoder!=="undefined";
function ob(a){var b=!1;b=b===void 0?!1:b;if(nb){if(b&&(mb?!a.isWellFormed():/(?:[^\uD800-\uDBFF]|^)[\uDC00-\uDFFF]|[\uD800-\uDBFF](?![\uDC00-\uDFFF])/.test(a)))throw Error("Found an unpaired surrogate");a=(lb||(lb=new TextEncoder)).encode(a)}else{for(var c=0,d=new Uint8Array(3*a.length),e=0;e<a.length;e++){var f=a.charCodeAt(e);if(f<128)d[c++]=f;else{if(f<2048)d[c++]=f>>6|192;else{if(f>=55296&&f<=57343){if(f<=56319&&e<a.length){var g=a.charCodeAt(++e);if(g>=56320&&g<=57343){f=(f-55296)*1024+g-56320+
65536;d[c++]=f>>18|240;d[c++]=f>>12&63|128;d[c++]=f>>6&63|128;d[c++]=f&63|128;continue}else e--}if(b)throw Error("Found an unpaired surrogate");f=65533}d[c++]=f>>12|224;d[c++]=f>>6&63|128}d[c++]=f&63|128}}a=c===d.length?d:d.subarray(0,c)}return a};function pb(a){Aa.setTimeout(function(){throw a;},0)};function qb(){var a=Aa.navigator;return a&&(a=a.userAgent)?a:""}var rb,sb=Aa.navigator;rb=sb?sb.userAgentData||null:null;var tb={},ub=null;function vb(a){var b=a.length,c=b*3/4;c%3?c=Math.floor(c):"=.".indexOf(a[b-1])!=-1&&(c="=.".indexOf(a[b-2])!=-1?c-2:c-1);var d=new Uint8Array(c),e=0;wb(a,function(f){d[e++]=f});return e!==c?d.subarray(0,e):d}
function wb(a,b){function c(k){for(;d<a.length;){var m=a.charAt(d++),n=ub[m];if(n!=null)return n;if(!/^[\s\xa0]*$/.test(m))throw Error("Unknown base64 encoding at char: "+m);}return k}xb();for(var d=0;;){var e=c(-1),f=c(0),g=c(64),h=c(64);if(h===64&&e===-1)break;b(e<<2|f>>4);g!=64&&(b(f<<4&240|g>>2),h!=64&&b(g<<6&192|h))}}
function xb(){if(!ub){ub={};for(var a="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),b=["+/=","+/","-_=","-_.","-_"],c=0;c<5;c++){var d=a.concat(b[c].split(""));tb[c]=d;for(var e=0;e<d.length;e++){var f=d[e];ub[f]===void 0&&(ub[f]=e)}}}};var yb=typeof Uint8Array!=="undefined",zb=!(Da&&rb&&rb.brands.length>0?0:qb().indexOf("Trident")!=-1||qb().indexOf("MSIE")!=-1)&&typeof btoa==="function",Ab=/[-_.]/g,Bb={"-":"+",_:"/",".":"="};function Cb(a){return Bb[a]||""}function Db(a){if(!zb)return vb(a);a=Ab.test(a)?a.replace(Ab,Cb):a;a=atob(a);for(var b=new Uint8Array(a.length),c=0;c<a.length;c++)b[c]=a.charCodeAt(c);return b}var Eb={};function Fb(a,b){Gb(b);this.g=a;if(a!=null&&a.length===0)throw Error("ByteString should be constructed with non-empty values");}function Hb(){return Ib||(Ib=new Fb(null,Eb))}function Jb(a){Gb(Eb);var b=a.g;b=b==null||yb&&b!=null&&b instanceof Uint8Array?b:typeof b==="string"?Db(b):null;return b==null?b:a.g=b}var Ib;function Gb(a){if(a!==Eb)throw Error("illegal external caller");};function Kb(a,b,c){this.buffer=a;if(c&&!b)throw Error();this.g=b}
function Lb(a,b){if(typeof a==="string")return new Kb(Db(a),b);if(Array.isArray(a))return new Kb(new Uint8Array(a),b);if(a.constructor===Uint8Array)return new Kb(a,!1);if(a.constructor===ArrayBuffer)return a=new Uint8Array(a),new Kb(a,!1);if(a.constructor===Fb)return b=Jb(a)||new Uint8Array(0),new Kb(b,!0,a);if(a instanceof Uint8Array)return a=a.constructor===Uint8Array?a:new Uint8Array(a.buffer,a.byteOffset,a.byteLength),new Kb(a,!1);throw Error();};function Nb(a,b,c,d){this.h=null;this.m=!1;this.g=this.i=this.l=0;this.init(a,b,c,d)}Nb.prototype.init=function(a,b,c,d){var e=d===void 0?{}:d;d=e.J===void 0?!1:e.J;e=e.L===void 0?!1:e.L;this.J=d;this.L=e;a&&(a=Lb(a,this.L),this.h=a.buffer,this.m=a.g,this.l=b||0,this.i=c!==void 0?this.l+c:this.h.length,this.g=this.l)};Nb.prototype.clear=function(){this.h=null;this.m=!1;this.g=this.i=this.l=0;this.J=!1};
function Ob(a,b){var c=0,d=0,e=0,f=a.h,g=a.g;do{var h=f[g++];c|=(h&127)<<e;e+=7}while(e<32&&h&128);if(e>32)for(d|=(h&127)>>4,e=3;e<32&&h&128;e+=7)h=f[g++],d|=(h&127)<<e;Pb(a,g);if(!(h&128))return b(c>>>0,d>>>0);throw Error();}function Pb(a,b){a.g=b;if(b>a.i)throw Error();}
function Qb(a){var b=a.h,c=a.g,d=b[c++],e=d&127;if(d&128&&(d=b[c++],e|=(d&127)<<7,d&128&&(d=b[c++],e|=(d&127)<<14,d&128&&(d=b[c++],e|=(d&127)<<21,d&128&&(d=b[c++],e|=d<<28,d&128&&b[c++]&128&&b[c++]&128&&b[c++]&128&&b[c++]&128&&b[c++]&128)))))throw Error();Pb(a,c);return e}function Rb(a){return Qb(a)>>>0}function Sb(a){a=Rb(a);return a>>>1^-(a&1)}function Tb(a){return Ob(a,Va)}function Ub(a){var b=a.h,c=a.g,d=b[c],e=b[c+1],f=b[c+2];b=b[c+3];Pb(a,a.g+4);return(d<<0|e<<8|f<<16|b<<24)>>>0}
function Vb(a){var b=Ub(a);a=(b>>31)*2+1;var c=b>>>23&255;b&=8388607;return c==255?b?NaN:a*Infinity:c==0?a*1.401298464324817E-45*b:a*Math.pow(2,c-150)*(b+8388608)}function Wb(a){var b=Ub(a),c=Ub(a);a=(c>>31)*2+1;var d=c>>>20&2047;b=4294967296*(c&1048575)+b;return d==2047?b?NaN:a*Infinity:d==0?a*4.9E-324*b:a*Math.pow(2,d-1075)*(b+4503599627370496)}function Xb(a){for(var b=0,c=a.g,d=c+10,e=a.h;c<d;){var f=e[c++];b|=f;if((f&128)===0)return Pb(a,c),!!(b&127)}throw Error();}
function Yb(a){return Qb(a)}function Zb(a,b){if(b<0)throw Error();var c=a.g;b=c+b;if(b>a.i)throw Error();a.g=b;return c}function $b(a,b){if(b==0)return Hb();var c=Zb(a,b);a.J&&a.m?c=a.h.subarray(c,c+b):(a=a.h,b=c+b,c=c===b?new Uint8Array(0):Ma?a.slice(c,b):new Uint8Array(a.subarray(c,b)));return c.length==0?Hb():new Fb(c,Eb)}var ac=[],bc=void 0;function cc(){this.g=[]}cc.prototype.length=function(){return this.g.length};cc.prototype.end=function(){var a=this.g;this.g=[];return a};function dc(a,b,c){for(;c>0||b>127;)a.g.push(b&127|128),b=(b>>>7|c<<25)>>>0,c>>>=7;a.g.push(b)}function ec(a,b){for(;b>127;)a.g.push(b&127|128),b>>>=7;a.g.push(b)}function fc(a,b){if(b>=0)ec(a,b);else{for(var c=0;c<9;c++)a.g.push(b&127|128),b>>=7;a.g.push(1)}}function A(a,b){a.g.push(b>>>0&255);a.g.push(b>>>8&255);a.g.push(b>>>16&255);a.g.push(b>>>24&255)};function hc(a,b,c,d){if(ac.length){var e=ac.pop();e.init(a,b,c,d);a=e}else a=new Nb(a,b,c,d);this.g=a;this.l=this.g.g;this.h=this.i=-1;this.setOptions(d)}hc.prototype.setOptions=function(a){a=a===void 0?{}:a;this.T=a.T===void 0?!1:a.T};function ic(a,b,c,d){if(jc.length){var e=jc.pop();e.setOptions(d);e.g.init(a,b,c,d);return e}return new hc(a,b,c,d)}function kc(a){a.g.clear();a.i=-1;a.h=-1;jc.length<100&&jc.push(a)}
function lc(a){var b=a.g;if(b.g==b.i)return!1;a.l=a.g.g;var c=Rb(a.g);b=c>>>3;c&=7;if(!(c>=0&&c<=5))throw Error();if(b<1)throw Error();a.i=b;a.h=c;return!0}function mc(a){switch(a.h){case 0:a.h!=0?mc(a):Xb(a.g);break;case 1:a=a.g;Pb(a,a.g+8);break;case 2:if(a.h!=2)mc(a);else{var b=Rb(a.g);a=a.g;Pb(a,a.g+b)}break;case 5:a=a.g;Pb(a,a.g+4);break;case 3:b=a.i;do{if(!lc(a))throw Error();if(a.h==4){if(a.i!=b)throw Error();break}mc(a)}while(1);break;default:throw Error();}}
function nc(a,b,c){var d=a.g.i,e=Rb(a.g);e=a.g.g+e;var f=e-d;f<=0&&(a.g.i=e,c(b,a,void 0,void 0,void 0),f=e-a.g.g);if(f)throw Error();a.g.g=e;a.g.i=d;return b}
function oc(a){var b=Rb(a.g);a=a.g;var c=Zb(a,b);a=a.h;if(kb){var d=a,e;(e=jb)||(e=jb=new TextDecoder("utf-8",{fatal:!0}));b=c+b;d=c===0&&b===d.length?d:d.subarray(c,b);try{var f=e.decode(d)}catch(m){if(ib===void 0){try{e.decode(new Uint8Array([128]))}catch(n){}try{e.decode(new Uint8Array([97])),ib=!0}catch(n){ib=!1}}!ib&&(jb=void 0);throw m;}}else{f=c;b=f+b;c=[];for(var g=null,h,k;f<b;)h=a[f++],h<128?c.push(h):h<224?f>=b?gb():(k=a[f++],h<194||(k&192)!==128?(f--,gb()):c.push((h&31)<<6|k&63)):h<240?
f>=b-1?gb():(k=a[f++],(k&192)!==128||h===224&&k<160||h===237&&k>=160||((e=a[f++])&192)!==128?(f--,gb()):c.push((h&15)<<12|(k&63)<<6|e&63)):h<=244?f>=b-2?gb():(k=a[f++],(k&192)!==128||(h<<28)+(k-144)>>30!==0||((e=a[f++])&192)!==128||((d=a[f++])&192)!==128?(f--,gb()):(h=(h&7)<<18|(k&63)<<12|(e&63)<<6|d&63,h-=65536,c.push((h>>10&1023)+55296,(h&1023)+56320))):gb(),c.length>=8192&&(g=hb(g,c),c.length=0);f=hb(g,c)}return f}function pc(a){var b=Rb(a.g);return $b(a.g,b)}
function qc(a,b,c){var d=Rb(a.g);for(d=a.g.g+d;a.g.g<d;)c.push(b(a.g))}var jc=[];function rc(){this.i=[];this.h=0;this.g=new cc}function sc(a,b){b.length!==0&&(a.i.push(b),a.h+=b.length)}function tc(a,b){B(a,b,2);b=a.g.end();sc(a,b);b.push(a.h);return b}function uc(a,b){var c=b.pop();for(c=a.h+a.g.length()-c;c>127;)b.push(c&127|128),c>>>=7,a.h++;b.push(c);a.h++}function B(a,b,c){ec(a.g,b*8+c)}function vc(a,b,c){c!=null&&(c=parseInt(c,10),B(a,b,0),fc(a.g,c))}function wc(a,b,c){B(a,b,2);ec(a.g,c.length);sc(a,a.g.end());sc(a,c)}
function xc(a,b,c,d){c!=null&&(b=tc(a,b),d(c,a),uc(a,b))}function yc(a){switch(typeof a){case "string":a.length&&a[0]==="-"?ab(a.substring(1)):ab(a)}};var zc=typeof Symbol==="function"&&typeof Symbol()==="symbol";function Ac(a,b,c){return typeof Symbol==="function"&&typeof Symbol()==="symbol"?(c===void 0?0:c)&&Symbol.for&&a?Symbol.for(a):a!=null?Symbol(a):Symbol():b}var Bc=Ac("jas",void 0,!0),Cc=Ac(void 0,"1oa"),Dc=Ac(void 0,Symbol()),Ec=Ac(void 0,"0ubs"),Fc=Ac(void 0,"0ubsb"),Gc=Ac(void 0,"0actk"),Hc=Ac("m_m","ba",!0);var Ic={aa:{value:0,configurable:!0,writable:!0,enumerable:!1}},Jc=Object.defineProperties,D=zc?Bc:"aa",Kc,Lc=[];E(Lc,7);Kc=Object.freeze(Lc);function Mc(a,b){zc||D in a||Jc(a,Ic);a[D]|=b}function E(a,b){zc||D in a||Jc(a,Ic);a[D]=b};var Nc={};function Oc(a,b){return b===void 0?a.g!==Pc&&!!(2&(a.j[D]|0)):!!(2&b)&&a.g!==Pc}var Pc={};function Qc(a,b,c){var d=b&128?0:-1,e=a.length,f;if(f=!!e)f=a[e-1],f=f!=null&&typeof f==="object"&&f.constructor===Object;var g=e+(f?-1:0);for(b=b&128?1:0;b<g;b++)c(b-d,a[b]);if(f){a=a[e-1];for(var h in a)!isNaN(h)&&c(+h,a[h])}}var Rc={};function Sc(a){return a&128?Rc:void 0};function Tc(a){return a};var Uc=void 0;function Vc(a,b){if(a!=null){var c;var d=(c=Uc)!=null?c:Uc={};c=d[a]||0;c>=b||(d[a]=c+1,a=Error(),a.__closure__error__context__984382||(a.__closure__error__context__984382={}),a.__closure__error__context__984382.severity="incident",pb(a))}};function Wc(a){return Array.prototype.slice.call(a)};var Xc=typeof BigInt==="function"?BigInt.asIntN:void 0,Yc=typeof BigInt==="function"?BigInt.asUintN:void 0,Zc=Number.isSafeInteger,$c=Number.isFinite,ad=Math.trunc;function bd(a){if(a!=null&&typeof a!=="number")throw Error("Value of float/double field must be a number, found "+typeof a+": "+a);return a}function cd(a){if(a==null||typeof a==="number")return a;if(a==="NaN"||a==="Infinity"||a==="-Infinity")return Number(a)}
function hd(a){if(a==null||typeof a==="boolean")return a;if(typeof a==="number")return!!a}var id=/^-?([1-9][0-9]*|0)(\.[0-9]+)?$/;function jd(a){switch(typeof a){case "bigint":return!0;case "number":return $c(a);case "string":return id.test(a);default:return!1}}function kd(a){if(a==null)return a;if(typeof a==="string"&&a)a=+a;else if(typeof a!=="number")return;return $c(a)?a|0:void 0}
function ld(a){if(a==null)return a;if(typeof a==="string"&&a)a=+a;else if(typeof a!=="number")return;return $c(a)?a>>>0:void 0}
function md(a){if(a==null)return a;var b=typeof a;if(b==="bigint")return String(Xc(64,a));if(jd(a)){if(b==="string")return b=ad(Number(a)),Zc(b)?a=String(b):(b=a.indexOf("."),b!==-1&&(a=a.substring(0,b)),b=a.length,(a[0]==="-"?b<20||b===20&&a<="-9223372036854775808":b<19||b===19&&a<="9223372036854775807")||(Xa(a),a=v,b=y,b&2147483648?Fa()?a=""+(BigInt(b|0)<<BigInt(32)|BigInt(a>>>0)):(b=q(Qa(a,b)),a=b.next().value,b=b.next().value,a="-"+Ua(a,b)):a=Ua(a,b))),a;if(b==="number")return a=ad(a),Zc(a)||
(Pa(a),a=Va(v,y)),a}}function nd(a){if(a==null)return a;var b=typeof a;if(b==="bigint")return String(Yc(64,a));if(jd(a)){if(b==="string")return b=ad(Number(a)),Zc(b)&&b>=0?a=String(b):(b=a.indexOf("."),b!==-1&&(a=a.substring(0,b)),a[0]==="-"?b=!1:(b=a.length,b=b<20?!0:b===20&&a<="18446744073709551615"),b||(Xa(a),a=Ua(v,y))),a;if(b==="number")return a=ad(a),a>=0&&Zc(a)||(Pa(a),a=Ta(v,y)),a}}function od(a){if(a==null||typeof a=="string"||a instanceof Fb)return a}
function pd(a){if(a!=null&&typeof a!=="string")throw Error();return a}function qd(a){return a==null||typeof a==="string"?a:void 0};function rd(a){var b=Ca(Dc);return b?a[b]:void 0}function sd(){}function td(a,b){for(var c in a)!isNaN(c)&&b(a,+c,a[c])}function ud(a){var b=new sd;td(a,function(c,d,e){b[d]=Wc(e)});b.g=a.g;return b}function vd(a,b){b<100||Vc(Ec,1)};function wd(a,b,c,d){var e=d!==void 0;d=!!d;var f=Ca(Dc),g;!e&&zc&&f&&(g=a[f])&&td(g,vd);f=[];var h=a.length;g=4294967295;var k=!1,m=!!(b&64),n=m?b&128?0:-1:void 0;if(!(b&1)){var w=h&&a[h-1];w!=null&&typeof w==="object"&&w.constructor===Object?(h--,g=h):w=void 0;if(m&&!(b&128)&&!e){k=!0;var x;g=((x=xd)!=null?x:Tc)(g-n,n,a,w,void 0)+n}}b=void 0;for(x=0;x<h;x++){var z=a[x];if(z!=null&&(z=c(z,d))!=null)if(m&&x>=g){var G=x-n,C=void 0;((C=b)!=null?C:b={})[G]=z}else f[x]=z}if(w)for(var S in w)h=w[S],h!=
null&&(h=c(h,d))!=null&&(x=+S,z=void 0,m&&!Number.isNaN(x)&&(z=x+n)<g?f[z]=h:(x=void 0,((x=b)!=null?x:b={})[S]=h));b&&(k?f.push(b):f[g]=b);e&&Ca(Dc)&&(a=rd(a))&&a instanceof sd&&(f[Dc]=ud(a));return f}
function yd(a){switch(typeof a){case "number":return Number.isFinite(a)?a:""+a;case "bigint":return(Ga?a>=Ia&&a<=Ka:a[0]==="-"?La(a,Ha):La(a,Ja))?Number(a):""+a;case "boolean":return a?1:0;case "object":if(Array.isArray(a)){var b=a[D]|0;return a.length===0&&b&1?void 0:wd(a,b,yd)}if(a!=null&&a[Hc]===Nc)return zd(a);if(a instanceof Fb){b=a.g;if(b==null)a="";else if(typeof b==="string")a=b;else{if(zb){for(var c="",d=0,e=b.length-10240;d<e;)c+=String.fromCharCode.apply(null,b.subarray(d,d+=10240));c+=
String.fromCharCode.apply(null,d?b.subarray(d):b);b=btoa(c)}else{c===void 0&&(c=0);xb();c=tb[c];d=Array(Math.floor(b.length/3));e=c[64]||"";for(var f=0,g=0;f<b.length-2;f+=3){var h=b[f],k=b[f+1],m=b[f+2],n=c[h>>2];h=c[(h&3)<<4|k>>4];k=c[(k&15)<<2|m>>6];m=c[m&63];d[g++]=n+h+k+m}n=0;m=e;switch(b.length-f){case 2:n=b[f+1],m=c[(n&15)<<2]||e;case 1:b=b[f],d[g]=c[b>>2]+c[(b&3)<<4|n>>4]+m+e}b=d.join("")}a=a.g=b}return a}return}return a}var xd;function zd(a){a=a.j;return wd(a,a[D]|0,yd)};var Ad,Bd;function Cd(a){switch(typeof a){case "boolean":return Ad||(Ad=[0,void 0,!0]);case "number":return a>0?void 0:a===0?Bd||(Bd=[0,void 0]):[-a,void 0];case "string":return[0,a];case "object":return a}}function Dd(a,b,c){return a=F(a,b[0],b[1],c?1:2)}
function F(a,b,c,d){d=d===void 0?0:d;if(a==null){var e=32;c?(a=[c],e|=128):a=[];b&&(e=e&-8380417|(b&1023)<<13)}else{if(!Array.isArray(a))throw Error("narr");e=a[D]|0;if(Ea&&1&e)throw Error("rfarr");2048&e&&!(2&e)&&Ed();if(e&256)throw Error("farr");if(e&64)return d!==0||e&2048||E(a,e|2048),a;if(c&&(e|=128,c!==a[0]))throw Error("mid");a:{c=a;e|=64;var f=c.length;if(f){var g=f-1,h=c[g];if(h!=null&&typeof h==="object"&&h.constructor===Object){b=e&128?0:-1;g-=b;if(g>=1024)throw Error("pvtlmt");for(var k in h)f=
+k,f<g&&(c[f+b]=h[k],delete h[k]);e=e&-8380417|(g&1023)<<13;break a}}if(b){k=Math.max(b,f-(e&128?0:-1));if(k>1024)throw Error("spvt");e=e&-8380417|(k&1023)<<13}}}e|=64;d===0&&(e|=2048);E(a,e);return a}function Ed(){if(Ea)throw Error("carr");Vc(Gc,5)};function Fd(a,b){if(typeof a!=="object")return a;if(Array.isArray(a)){var c=a[D]|0;a.length===0&&c&1?a=void 0:c&2||(!b||4096&c||16&c?a=Gd(a,c,!1,b&&!(c&16)):(Mc(a,34),c&4&&Object.freeze(a)));return a}if(a!=null&&a[Hc]===Nc)return b=a.j,c=b[D]|0,Oc(a,c)?a:Hd(a,b,c)?Id(a,b):Gd(b,c);if(a instanceof Fb)return a}function Id(a,b,c){a=new a.constructor(b);c&&(a.g=Pc);a.h=Pc;return a}function Gd(a,b,c,d){d!=null||(d=!!(34&b));a=wd(a,b,Fd,d);d=32;c&&(d|=2);b=b&8380609|d;E(a,b);return a}
function Jd(a){if(a.g!==Pc)return!1;var b=a.j;b=Gd(b,b[D]|0);Mc(b,2048);a.j=b;a.g=void 0;a.h=void 0;return!0}function Kd(a){if(!Jd(a)&&Oc(a,a.j[D]|0))throw Error();}function Ld(a,b){b===void 0&&(b=a[D]|0);b&32&&!(b&4096)&&E(a,b|4096)}function Hd(a,b,c){return c&2?!0:c&32&&!(c&4096)?(E(b,c|2),a.g=Pc,!0):!1};function Md(a,b,c){a=Nd(a.j,b,void 0,c);if(a!==null)return a}function Nd(a,b,c,d){if(b===-1)return null;var e=b+(c?0:-1),f=a.length-1;if(!(f<1+(c?0:-1))){if(e>=f){var g=a[f];if(g!=null&&typeof g==="object"&&g.constructor===Object){c=g[b];var h=!0}else if(e===f)c=g;else return}else c=a[e];if(d&&c!=null){d=d(c);if(d==null)return d;if(!Object.is(d,c))return h?g[b]=d:a[e]=d,d}return c}}function Od(a,b,c){Kd(a);var d=a.j;H(d,d[D]|0,b,c);return a}
function H(a,b,c,d,e){var f=c+(e?0:-1),g=a.length-1;if(g>=1+(e?0:-1)&&f>=g){var h=a[g];if(h!=null&&typeof h==="object"&&h.constructor===Object)return h[c]=d,b}if(f<=g)return a[f]=d,b;if(d!==void 0){var k;g=((k=b)!=null?k:b=a[D]|0)>>13&1023||536870912;c>=g?d!=null&&(f={},a[g+(e?0:-1)]=(f[c]=d,f)):a[f]=d}return b}function Pd(a,b){return Qd(a,a[D]|0,b)}
function Rd(a){return a==null?a:typeof a==="string"?a?new Fb(a,Eb):Hb():a.constructor===Fb?a:yb&&a!=null&&a instanceof Uint8Array?a.length?new Fb(new Uint8Array(a),Eb):Hb():void 0}function Qd(a,b,c){if(b&2)throw Error();var d=Sc(b);var e=Nd(a,c,d);e=Array.isArray(e)?e:Kc;var f=e===Kc?7:e[D]|0;var g=f;2&b&&(g|=2);g|=1;if(2&g||2&g&&4&g||256&g||16&g)e=Wc(e),f=0,g=Sd(g,b),H(a,b,c,e,d);g&=-13;g!==f&&E(e,g);return e}
function Td(a,b,c,d){Kd(a);var e=a.j,f=e[D]|0;if(d==null){var g=Ud(e);if(Vd(g,e,f,c)===b)g.set(c,0);else return a}else f=Wd(e,f,c,b);H(e,f,b,d);return a}function Xd(a,b,c,d){var e=a[D]|0,f=Sc(e);e=Wd(a,e,c,b,f);H(a,e,b,d,f)}function Ud(a){if(zc){var b;return(b=a[Cc])!=null?b:a[Cc]=new Map}if(Cc in a)return a[Cc];b=new Map;Object.defineProperty(a,Cc,{value:b});return b}function Wd(a,b,c,d,e){var f=Ud(a),g=Vd(f,a,b,c,e);g!==d&&(g&&(b=H(a,b,g,void 0,e)),f.set(c,d));return b}
function Vd(a,b,c,d,e){var f=a.get(d);if(f!=null)return f;for(var g=f=0;g<d.length;g++){var h=d[g];Nd(b,h,e)!=null&&(f!==0&&(c=H(b,c,f,void 0,e)),f=h)}a.set(d,f);return f}function Yd(a,b,c){var d=a[D]|0,e=Sc(d),f=Nd(a,c,e);if(f!=null&&f[Hc]===Nc){if(!Oc(f))return Jd(f),f.j;var g=f.j}else Array.isArray(f)&&(g=f);if(g){var h=g[D]|0;h&2&&(g=Gd(g,h))}g=Dd(g,b,!0);g!==f&&H(a,d,c,g,e);return g}
function Zd(a,b){var c=$d,d=!1,e=Nd(a,4,void 0,function(f){if(f!=null&&f[Hc]===Nc)var g=f;else if(Array.isArray(f)){g=f[D]|0;var h=g|b&32;h|=b&2;h!==g&&E(f,h);g=new c(f)}else g=void 0;d=g!==f&&g!=null;return g});if(e!=null)return d&&!Oc(e)&&Ld(a,b),e}function ae(a){var b=a.j,c=b[D]|0,d=Zd(b,c);if(d==null)return d;c=b[D]|0;if(!Oc(a,c)){var e=d;var f=e.j,g=f[D]|0;e=Oc(e,g)?Hd(e,f,g)?Id(e,f,!0):new e.constructor(Gd(f,g,!1)):e;e!==d&&(Jd(a)&&(b=a.j,c=b[D]|0),d=e,c=H(b,c,4,d),Ld(b,c))}return d}
function be(a){a==null&&(a=void 0);return a}function ce(a,b,c){c=be(c);Od(a,b,c);c&&!Oc(c)&&Ld(a.j);return a}function de(a,b){Kd(a);var c=a.j,d=c[D]|0;if(b==null)return H(c,d,1),a;for(var e=b===Kc?7:b[D]|0,f=e,g=!!(2&e)&&!!(4&e)||!!(256&e),h=g||Object.isFrozen(b),k=!0,m=!0,n=0;n<b.length;n++){var w=b[n];g||(w=Oc(w),k&&(k=!w),m&&(m=w))}g||(e=k?13:5,e=m?e&-4097:e|4096);h&&e===f||(b=Wc(b),f=0,e=Sd(e,d));e!==f&&E(b,e);d=H(c,d,1,b);2&e||!(4096&e||16&e)||Ld(c,d);return a}
function Sd(a,b){return a=(2&b?a|2:a&-3)&-273};function I(a,b,c){this.j=F(a,b,c)}I.prototype.toJSON=function(){var a=zd(this);return a};I.prototype[Hc]=Nc;I.prototype.toString=function(){return this.j.toString()};function J(){function a(){throw Error();}Object.setPrototypeOf(a,a.prototype);return a}var ee=J(),fe=J(),ge=J(),he=J(),ie=J(),je=J(),ke=J(),le=J(),me=J(),ne=J();function oe(a,b,c){this.g=a;this.h=b;a=Ca(ee);this.i=!!a&&c===a||!1}function pe(a,b){var c=c===void 0?ee:c;return new oe(a,b,c)}function qe(a,b,c,d,e){xc(a,c,re(b,d),e)}var se=pe(function(a,b,c,d,e){if(a.h!==2)return!1;nc(a,Yd(b,d,c),e);return!0},qe),te=pe(function(a,b,c,d,e){if(a.h!==2)return!1;nc(a,Yd(b,d,c),e);return!0},qe),ue=Symbol(),ve=Symbol(),we=Symbol(),xe=Symbol(),ye=Symbol(),ze,Ae;
function Be(a,b,c,d){var e=d[a];if(e)return e;e={};e.Z=d;e.I=Cd(d[0]);var f=d[1],g=1;f&&f.constructor===Object&&(e.U=f,f=d[++g],typeof f==="function"&&(e.X=!0,ze!=null||(ze=f),Ae!=null||(Ae=d[g+1]),f=d[g+=2]));for(var h={};f&&Array.isArray(f)&&f.length&&typeof f[0]==="number"&&f[0]>0;){for(var k=0;k<f.length;k++)h[f[k]]=f;f=d[++g]}for(k=1;f!==void 0;){typeof f==="number"&&(k+=f,f=d[++g]);var m=void 0;if(f instanceof oe)var n=f;else n=se,g--;f=void 0;if((f=n)==null?0:f.i){f=d[++g];m=d;var w=g;typeof f===
"function"&&(f=f(),m[w]=f);m=f}f=d[++g];w=k+1;typeof f==="number"&&f<0&&(w-=f,f=d[++g]);for(;k<w;k++){var x=h[k];m?c(e,k,n,m,x):b(e,k,n,x)}}return d[a]=e}function Ce(a){return Array.isArray(a)?a[0]instanceof oe?a:[te,a]:[a,void 0]}function re(a,b){if(a instanceof I)return a.j;if(Array.isArray(a))return Dd(a,b,!1)};function De(a,b,c,d){var e=c.g;a[b]=d?function(f,g,h){return e(f,g,h,d)}:e}function Ee(a,b,c,d,e){var f=c.g,g,h;a[b]=function(k,m,n){return f(k,m,n,h||(h=Be(ve,De,Ee,d).I),g||(g=Fe(d)),e)}}
function Fe(a){var b=a[we];if(b!=null)return b;var c=Be(ve,De,Ee,a);b=c.X?function(d,e){return ze(d,e,c)}:function(d,e){for(;lc(e)&&e.h!=4;){var f=e.i,g=c[f];if(g==null){var h=c.U;h&&(h=h[f])&&(h=Ge(h),h!=null&&(g=c[f]=h))}if(g==null||!g(e,d,f)){h=e;g=h.l;mc(h);if(h.T)var k=void 0;else{var m=h.g.g-g;h.g.g=g;k=$b(h.g,m)}m=h=g=void 0;var n=d;k&&((g=(h=(m=n[Dc])!=null?m:n[Dc]=new sd)[f])!=null?g:h[f]=[]).push(k)}}if(d=rd(d))d.g=c.Z[ye];return!0};a[we]=b;a[ye]=He.bind(a);return b}
function He(a,b,c,d){var e=this[ve],f=this[we],g=Dd(void 0,e.I,!1),h=rd(a);if(h){var k=!1,m=e.U;if(m){e=function(G,C,S){if(S.length!==0)if(m[C])for(G=q(S),C=G.next();!C.done;C=G.next()){C=ic(C.value);try{k=!0,f(g,C)}finally{kc(C)}}else d==null||d(a,C,S)};if(b==null)td(h,e);else if(h!=null){var n=h[b];n&&e(h,b,n)}if(k){var w=a[D]|0;if(w&2&&w&2048&&(c==null||!c.da))throw Error();var x=Sc(w),z=function(G,C){if(Nd(a,G,x)!=null)switch(c==null?void 0:c.ca){case 1:return;default:throw Error();}C!=null&&
(w=H(a,w,G,C,x));delete h[G]};b==null?Qc(g,g[D]|0,function(G,C){z(G,C)}):z(b,Nd(g,b,x))}}}}function Ge(a){a=Ce(a);var b=a[0].g;if(a=a[1]){var c=Fe(a),d=Be(ve,De,Ee,a).I;return function(e,f,g){return b(e,f,g,d,c)}}return b};function Ie(a,b,c){a[b]=c.h}function Je(a,b,c,d){var e,f,g=c.h;a[b]=function(h,k,m){return g(h,k,m,f||(f=Be(ue,Ie,Je,d).I),e||(e=Ke(d)))}}function Ke(a){var b=a[xe];if(!b){var c=Be(ue,Ie,Je,a);b=function(d,e){return Le(d,e,c)};a[xe]=b}return b}function Le(a,b,c){Qc(a,a[D]|0,function(d,e){if(e!=null){var f=Me(c,d);f?f(b,e,d):d<500||Vc(Fc,3)}});(a=rd(a))&&td(a,function(d,e,f){sc(b,b.g.end());for(d=0;d<f.length;d++)sc(b,Jb(f[d])||new Uint8Array(0))})}
function Me(a,b){var c=a[b];if(c)return c;if(c=a.U)if(c=c[b]){c=Ce(c);var d=c[0].h;if(c=c[1]){var e=Ke(c),f=Be(ue,Ie,Je,c).I;c=a.X?Ae(f,e):function(g,h,k){return d(g,h,k,f,e)}}else c=d;return a[b]=c}};function K(a,b,c){if(Array.isArray(b)){var d=b[D]|0;if(d&4)return b;for(var e=0,f=0;e<b.length;e++){var g=a(b[e]);g!=null&&(b[f++]=g)}f<e&&(b.length=f);c&&(E(b,(d|5)&-1537),d&2&&Object.freeze(b));return b}}function L(a,b,c){return new oe(a,b,c)}function M(a,b,c){return new oe(a,b,c)}function N(a,b,c){H(a,a[D]|0,b,c,Sc(a[D]|0))}
var Ne=pe(function(a,b,c,d,e){if(a.h!==2)return!1;a=nc(a,Dd([void 0,void 0],d,!0),e);a=Wc(a);d=b[D]|0;e=Sc(d);if(d&2)throw Error();var f=Nd(b,c,e);if(Array.isArray(f)){if((f[D]|0)&2){f=Wc(f);for(var g=0;g<f.length;g++){var h=f[g]=Wc(f[g]);if(Array.isArray(h[1])){var k=h[1];Mc(k,34);h[1]=k}}H(b,d,c,f,e)}f.push(a)}else H(b,d,c,[a],e);return!0},function(a,b,c,d,e){if(Array.isArray(b))for(var f=0;f<b.length;f++){var g=b[f];Array.isArray(g)&&xc(a,c,Dd(g,d,!1),e)}});
function Oe(a,b,c){b=cd(b);b!=null&&(B(a,c,1),a=a.g,Sa(b),A(a,v),A(a,y))}function Pe(a,b,c){b=cd(b);b!=null&&(B(a,c,5),a=a.g,Ra(b),A(a,v))}function Qe(a,b,c){b=md(b);if(b!=null){switch(typeof b){case "string":eb(b)}if(b!=null)switch(B(a,c,0),typeof b){case "number":a=a.g;Pa(b);dc(a,v,y);break;case "bigint":c=db(b);dc(a.g,c.h,c.g);break;default:c=eb(b),dc(a.g,c.h,c.g)}}}
function Re(a,b,c){b=nd(b);if(b!=null){switch(typeof b){case "string":ab(b)}if(b!=null)switch(B(a,c,0),typeof b){case "number":a=a.g;Pa(b);dc(a,v,y);break;case "bigint":c=$a(b);dc(a.g,c.h,c.g);break;default:c=ab(b),dc(a.g,c.h,c.g)}}}function Se(a,b,c){b=kd(b);b!=null&&b!=null&&(B(a,c,0),fc(a.g,b))}function Te(a,b,c){b=hd(b);b!=null&&(B(a,c,0),a.g.g.push(b?1:0))}function Ue(a,b,c){b=qd(b);b!=null&&wc(a,c,ob(b))}function Ve(a,b,c,d,e){xc(a,c,re(b,d),e)}function We(a,b,c){vc(a,c,kd(b))}
function Xe(a,b,c){if(a.h!==5&&a.h!==2)return!1;b=Pd(b,c);a.h==2?qc(a,Vb,b):b.push(Vb(a.g));return!0}function Ye(a,b,c){if(a.h!==0&&a.h!==2)return!1;b=Pd(b,c);a.h==2?qc(a,Qb,b):b.push(Qb(a.g));return!0}function Ze(a,b,c){if(a.h!==0&&a.h!==2)return!1;b=Pd(b,c);a.h==2?qc(a,Xb,b):b.push(Xb(a.g));return!0}
var $e=L(function(a,b,c,d){if(a.h!==1)return!1;Xd(b,c,d,Wb(a.g));return!0},Oe,le),O=L(function(a,b,c){if(a.h!==5)return!1;N(b,c,Vb(a.g));return!0},Pe,ke),af=M(Xe,function(a,b,c){b=K(cd,b,!0);if(b!=null)for(var d=0;d<b.length;d++){var e=a,f=c,g=b[d];g!=null&&(B(e,f,5),e=e.g,Ra(g),A(e,v))}},ke),P=M(Xe,function(a,b,c){b=K(cd,b,!0);if(b!=null&&b.length)for(B(a,c,2),ec(a.g,b.length*4),c=0;c<b.length;c++){var d=a.g;Ra(b[c]);A(d,v)}},ke),bf=L(function(a,b,c,d){if(a.h!==5)return!1;Xd(b,c,d,Vb(a.g));return!0},
Pe,ke),cf=L(function(a,b,c){if(a.h!==0)return!1;N(b,c,Tb(a.g));return!0},Qe,ie),df=M(function(a,b,c){if(a.h!==0&&a.h!==2)return!1;b=Pd(b,c);a.h==2?qc(a,Tb,b):b.push(Tb(a.g));return!0},function(a,b,c){b=K(md,b,!1);if(b!=null&&b.length){c=tc(a,c);for(var d=0;d<b.length;d++){var e=b[d];switch(typeof e){case "number":var f=a.g;Pa(e);dc(f,v,y);break;case "bigint":e=db(e);dc(a.g,e.h,e.g);break;default:e=eb(e),dc(a.g,e.h,e.g)}}uc(a,c)}},ie),ef=L(function(a,b,c,d){if(a.h!==0)return!1;Xd(b,c,d,Tb(a.g));return!0},
Qe,ie),ff=L(function(a,b,c){if(a.h!==0)return!1;N(b,c,Ob(a.g,Ua));return!0},Re,je),gf=L(function(a,b,c){if(a.h!==0)return!1;N(b,c,Ob(a.g,Ta));return!0},Re,je),Q=L(function(a,b,c){if(a.h!==0)return!1;N(b,c,Qb(a.g));return!0},Se,he),hf=M(Ye,function(a,b,c){b=K(kd,b,!0);if(b!=null)for(var d=0;d<b.length;d++){var e=a,f=c,g=b[d];g!=null&&(B(e,f,0),fc(e.g,g))}},he),jf=M(Ye,function(a,b,c){b=K(kd,b,!0);if(b!=null&&b.length){c=tc(a,c);for(var d=0;d<b.length;d++)fc(a.g,b[d]);uc(a,c)}},he),kf=L(function(a,
b,c,d){if(a.h!==0)return!1;Xd(b,c,d,Qb(a.g));return!0},Se,he),R=L(function(a,b,c){if(a.h!==0)return!1;N(b,c,Xb(a.g));return!0},Te,fe),lf=M(Ze,function(a,b,c){b=K(hd,b,!0);if(b!=null)for(var d=0;d<b.length;d++){var e=a,f=c,g=b[d];g!=null&&(B(e,f,0),e.g.g.push(g?1:0))}},fe),mf=M(Ze,function(a,b,c){b=K(hd,b,!0);if(b!=null&&b.length)for(B(a,c,2),ec(a.g,b.length),c=0;c<b.length;c++)a.g.g.push(b[c]?1:0)},fe),nf=L(function(a,b,c,d){if(a.h!==0)return!1;Xd(b,c,d,Xb(a.g));return!0},Te,fe),T=L(function(a,b,
c){if(a.h!==2)return!1;N(b,c,oc(a));return!0},Ue,ge),of=L(function(a,b,c,d){if(a.h!==2)return!1;Xd(b,c,d,oc(a));return!0},Ue,ge),U=M(function(a,b,c){if(a.h!==2)return!1;a=oc(a);Qd(b,b[D]|0,c).push(a);return!0},function(a,b,c){b=K(qd,b,!0);if(b!=null)for(var d=0;d<b.length;d++){var e=a,f=c,g=b[d];g!=null&&wc(e,f,ob(g))}},ge),V,pf=void 0;pf=pf===void 0?ee:pf;
V=new oe(function(a,b,c,d,e){if(a.h!==2)return!1;d=Dd(void 0,d,!0);Qd(b,b[D]|0,c).push(d);nc(a,d,e);return!0},function(a,b,c,d,e){if(Array.isArray(b))for(var f=0;f<b.length;f++)Ve(a,b[f],c,d,e)},pf);
var W=pe(function(a,b,c,d,e,f){if(a.h!==2)return!1;var g=b[D]|0;Wd(b,g,f,c,Sc(g));b=Yd(b,d,c);nc(a,b,e);return!0},Ve),qf=L(function(a,b,c){if(a.h!==2)return!1;N(b,c,pc(a));return!0},function(a,b,c){b=od(b);b!=null&&wc(a,c,Lb(b,!0).buffer)},me),X=L(function(a,b,c){if(a.h!==0)return!1;N(b,c,Rb(a.g));return!0},function(a,b,c){b=ld(b);b!=null&&b!=null&&(B(a,c,0),ec(a.g,b))},J()),Y=L(function(a,b,c){if(a.h!==0)return!1;N(b,c,Qb(a.g));return!0},We,ne),rf=M(function(a,b,c){if(a.h!==0&&a.h!==2)return!1;b=
Pd(b,c);a.h==2?qc(a,Yb,b):b.push(Qb(a.g));return!0},function(a,b,c){b=K(kd,b,!0);if(b!=null)for(var d=0;d<b.length;d++)vc(a,c,b[d])},ne),sf=L(function(a,b,c,d){if(a.h!==0)return!1;Xd(b,c,d,Qb(a.g));return!0},We,ne),tf=M(function(a,b,c){if(a.h!==0&&a.h!==2)return!1;b=Pd(b,c);a.h==2?qc(a,Sb,b):b.push(Sb(a.g));return!0},function(a,b,c){b=K(kd,b,!0);if(b!=null)for(var d=0;d<b.length;d++){var e=a,f=c,g=b[d];g!=null&&(B(e,f,0),ec(e.g,(g<<1^g>>31)>>>0))}},J()),uf=[!0,T,Q],vf=[!0,T,R],wf=[!0,T,T];function xf(a){return function(b){var c=new rc;Le(b.j,c,Be(ue,Ie,Je,a));sc(c,c.g.end());b=new Uint8Array(c.h);for(var d=c.i,e=d.length,f=0,g=0;g<e;g++){var h=d[g];b.set(h,f);f+=h.length}c.i=[b];return b}};var yf=[0,L(function(a,b,c){if(a.h!==1)return!1;var d=a.g;a=Ub(d);d=Ub(d);N(b,c,Ua(a,d));return!0},function(a,b,c){b=nd(b);if(b!=null)switch(yc(b),B(a,c,1),a=a.g,yc(b),typeof b){case "number":b<0?(c=-b,c=Za(new Ya(c&4294967295,c/4294967296)),b=c.g,A(a,c.h),A(a,b)):(Oa(b),A(a,v),A(a,y));break;case "bigint":c=b<BigInt(0)?Za($a(-b)):$a(b);b=c.g;A(a,c.h);A(a,b);break;default:c=b.length&&b[0]==="-"?Za(ab(b.substring(1))):ab(b),b=c.g,A(a,c.h),A(a,b)}},J()),-1];var zf=[0,L(function(a,b,c){if(a.h!==5)return!1;a=a.g;var d=a.h,e=a.g,f=d[e],g=d[e+1],h=d[e+2];d=d[e+3];Pb(a,a.g+4);N(b,c,f<<0|g<<8|h<<16|d<<24);return!0},function(a,b,c){b=kd(b);b!=null&&(B(a,c,5),a=a.g,a.g.push(b>>>0&255),a.g.push(b>>>8&255),a.g.push(b>>>16&255),a.g.push(b>>>24&255))},J()),-1];var Af=[0,Y,-1,cf,T,zf,-1,O,Q,Y,yf,T,Y,-1,[0,zf,-1],Q,gf,yf,O,[0,1,Q,-4,L(function(a,b,c){if(a.h!==1)return!1;N(b,c,Wb(a.g));return!0},Oe,le),[0,O,-1,Q],T,O,V,[0,Y,Q],Q,-1,Y,-2,O,-1,Y,O,Y,Q,[0,3,Q,-1,4,M(function(a,b,c){if(a.h!==2)return!1;a=pc(a);Qd(b,b[D]|0,c).push(a);return!0},function(a,b,c){b=K(od,b,!1);if(b!=null)for(var d=0;d<b.length;d++){var e=a,f=c,g=b[d];g!=null&&wc(e,f,Lb(g,!0).buffer)}},me)]],T,rf,V,[0,yf,V,[0,T,Y],O,Y,-1],1,V,[0,gf,-1,X],Y,yf];var Bf=[0,cf,[0,O,T,Q,T,Q,hf,cf,T,Q,T,-1,O,Q,O],qf,[0,M(function(a,b,c){if(a.h!==1&&a.h!==2)return!1;b=Pd(b,c);if(a.h==2){c=a.g;a=Rb(a.g)/8;var d=c.g,e=8*a;if(d+e>c.i)throw Error();var f=c.h;d+=f.byteOffset;bc===void 0&&(bc=(new Uint16Array((new Uint8Array([1,2])).buffer))[0]==513);if(bc)for(c.g+=e,c=new Float64Array(f.buffer.slice(d,d+e)),a=0;a<c.length;a++)b.push(c[a]);else for(e=0;e<a;e++)b.push(Wb(c))}else b.push(Wb(a.g));return!0},function(a,b,c){b=K(cd,b,!0);if(b!=null)for(var d=0;d<b.length;d++){var e=
a,f=c,g=b[d];g!=null&&(B(e,f,1),e=e.g,Sa(g),A(e,v),A(e,y))}},le),-1]];function $d(a){this.j=F(a)}p($d,I);function Cf(a){a=Md(a,1,Rd);return a==null?Hb():a}function Df(a){var b=16E3;b=b===void 0?0:b;a=kd(Md(a,2));return a!=null?a:b};function Ef(a){this.j=F(a)}p(Ef,I);function Ff(a){this.j=F(a)}p(Ff,I);var Gf=[0,qf,Q];var Hf=[0,[1,2,3,4],of,sf,W,[0,T,Y],sf];var If=[0,T,-5,O,T,U,Y,-1,V,Hf,T,-2];var Jf=[0,Q,-3];var Kf=[0,[1,2,3,4],nf,-1,of,-1];var Lf=[0,T,-1,1,T,-1,6,U,[0,X,T,X,Q,X,-4,O,X,O,-1],R,U,-1];var Z=[0,Y,-5];var Mf=[0,[0,T,-5,R,U,Z],T,-7,R,T,U,Z];var Nf=[0,U,1,Y,-1,T];var Qf=[0,T,-2,Z,T];var Rf=[0,T,-1,R,T,U,Z];var Sf=[0,V,[0,T,-1],T,R,T];var Tf=[0,T,-2,Z];var Uf=[0,T,-3,Q,T,R,T,-1,R,T,U,Z,T,-2];var Vf=[0,R,T,-3,Q,T,R,T,U,Z];var Wf=[0,T,-3,Q,T,-3,R,T,U,Z];var Xf=[0,T,Q,Y,T];var Yf=[0,T,-2,Q,T,R,T,R,U,Z];var Zf=[0,T,-2,R];var $f=[0,Vf,Yf,Rf,T,Q,T,R,T,U,Z];var ag=[0,Vf,cf,T,Q,T,R,T,U,Z,T];var bg=[0,T,-1,R,T,U,Z,R];var cg=[0,T,Q,R];var dg=[0,T,U,T,Q,T,R,T,U,Z];var eg=[0,Q,-2,R,T,Q,T,Q,T,R,T,U,Z,R];var fg=[0,Y,-1];var gg=[0,O,-1];var hg=[0,V,[0,O,-2],O,-1,Q,V,[0,Q,Y,Q,Y,X,Y,-1,V,gg,[0,O,-1],[0,V,gg,O,Y],[0,V,gg,Y]],O];var ig=[0,O,-2];var jg=[-11,{},Jf,T,[0,mf,jf,P,U,V,[0,P],[0,P]],P,T,-1,[0,ig],T,[0,P,-1,V,[0,Y,Q]],-1];var kg=[0,Jf,[0,R,O,P,-1],Q,[0,P]];var lg=[0,Y,[0,hf,df]];var mg=[0,Y,[0,hf,U]];var ng=[0,Q,-1,Y,Q];var og=[0,P,jf];var pg=[0,P,jf,T];var qg=[0,[0,ff,Y,R]];var rg=[0,Q,-2,T];var sg=[0,Y];var ug=[-15,{},V,[-45,{},[1,3,4,5,6,7,8,9,10,11,12,13,14,15,16,18,19,21,25,32,36,37,41],of,T,W,Rf,W,bg,W,Vf,W,Yf,W,eg,W,$f,W,Uf,W,Mf,W,dg,W,ag,W,Wf,W,Sf,of,-1,V,Zf,of,-1,hg,bf,[0,R,-1,Y,fg,R,-1,O,R,U,ng,Y,-1],Af,R,W,[0,T,-1],V,[0,T,-1],[0,U,R],Z,Y,sg,R,W,cg,T,U,T,W,Tf,W,Qf,T,-1,R,W,Xf,R,rg,T],V,[0,T,V,[0,T,-1,Y],V,[0,T,-1],T,Y,[0,Y,-3],U,R,T],4,sg,O,R,function(){return tg},T,qg,R,[0,R,-1]],tg=[0,V,function(){return ug},-1];var vg=function(a,b){return function(c,d){var e={L:!0};d&&Object.assign(e,d);c=ic(c,void 0,void 0,e);try{var f=new a,g=f.j;Fe(b)(g,c);var h=f}finally{kc(c)}return h}}(Ff,[0,Y,2,Gf,Y,[-500,{},gf,T,ug,-1,1,[0,Y,Q,-1,O],[0,T,-5,Q,T,1,R,-1,T,Y,V,If,T],cf,-2,89,[-5,{},V,[-75,{},Jf,X,-1,T,Y,T,-2,R,O,Y,T,R,-1,5,Rf,bg,T,Vf,Yf,eg,$f,Vf,Uf,Mf,dg,ag,Wf,T,-1,Tf,T,Qf,1,Sf,Xf,[0,T,-1],V,Zf,7,Lf,1,T,R,T,R,cg,T,R,T,-2,Kf,T,R,O,U,1,T,R,1,T,Nf,Y,R],V,[-71,{},Jf,Y,T,-1,R,1,T,Y,Lf,O,Y,R,rf,T,fg,1,Q,R,1,T,Y,O,[0,[0,O,
-2],[0,O,-2]],[0,Y,-2],25,hg,T,3,R,-1,1,R,T,2,R,Kf,T,Y,O,T,-1,1,T],V,[-11,{},Jf,T,Y,5,[0,Q,-3],T],V,[-12,{},Jf,T,R,O,-1,[0,O,-6,V,[0,T,Y,O]],af,Q,-1,T,[0,[0,Q,-3],V,[0,T,O]]]],1,[0,3,V,[0,V,[0,Q,-2]],R],3,ng,Y,-1,1,[-12,{},ng,Y,-1,[0,Y,2,Y,-1],Y,-1,T,3,[0,R,-2]],39,[0,[0,Q,-2,jf,-2],mg,-2,lg,mg,-2,lg,-5],49,[-3,{},[0,V,jg,[0,V,[0,T,V,[0,Q,O,V,[0,Q,O,-1,Q],R],V,[0,Q,O],R,-2]]],V,[0,Q,V,[0,Jf,[-10,{},Q,-2,X,[0,X,-2,O,-8,af,-5,tf,-1],rf,Q,-2],ig,O,-2,V,[0,Y,af]]]],[-3,{},[0,V,jg],V,[-6,{},V,kg,V,ig,
hf,lf,jf]],48,[0,[0,V,kg,Bf],[0,O,X,-1,O,X]],49,Gf,599,[-1,{}],R,[0,O,-2,Q],[-3,{},V,[-7,{},X,-1,R,V,[0,[1,2,3,4],W,[-5,{},Y,T,-1,R],W,[0],W,[0],W,[0]],O,X],X],og,V,pg]]);var wg=xf(If);function xg(a){this.j=F(a)}p(xg,I);var yg=[1,4];function zg(a){this.j=F(a,11)}p(zg,I);var Ag=[0,Q,qf,Y];var Bg=[-11,{},[0,V,[0,Y,1,Y],rf,Af,U,V,[0,T,Y,O,Y],1,Y,-1,R],[0,T,-3,O,[0,Q,T],rf,-1],[0,yg,bf,[0,Y],[0,2,Y],sf,[0,R,-1],O,Y,-2],[0,1,O,V,[0,T,-1],rf,qg,Q],Nf,[-1,{}],[0,[1,3],W,[0,[3,4],V,Hf,-1,kf,nf,V,Hf],T,of],[0,[1,2,3,4,5,6,7,8,9,10,11],sf,-10],[0,[1,2],[3,4,5],W,Ag,W,og,W,Ag,W,og,W,[0,P]],[0,[1],W,og,V,pg,Ag]];var Cg=[-3,{},T,Bg];function Dg(a){this.j=F(a)}p(Dg,I);function Eg(a){this.j=F(a,5)}p(Eg,I);function Fg(a){this.j=F(a)}p(Fg,I);var Gg=[2,3,4];var Hg=[0,T,-2];var Ig=[0,[3,4],T,-1,ef,$e,Q,-1,T,-1];var Jg=[0,Gg,Q,W,[-5,{},V,[0,[100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120],Q,T,-1,Bg,V,[0,[4,5],Q,T,-1,sf,of,T,Bg,Y],T,-1,rg,R,90,of,W,[0,T,Y,[0,Y,O,Y]],W,[0,T],W,[0,T,Q],W,[0,T,Y],W,[0,T,-1],W,[0,T,Y],W,Ig,W,[0,1,T],W,Hg,W,[0,U,Y],W,[0,[5,6,7],Q,-2,T,sf,-1,kf],W,[0,[5,6],Q,-3,sf,kf],W,[0,[1,2],[4,5,6],W,Ig,W,Hg,T,sf,-1,kf],W,[0,[3,4],[8,9,10],Q,-1,kf,of,Q,Y,T,sf,-1,kf],W,[0,T,U,T],W,[0,[4,5,6],Ig,T,1,sf,-1,kf],W,[0,T,-3,Q,T,-2],W,[0,T,Y],W,[0,V,[0,T,-1],T,
R],W,[0,T,-1]],Bg,V,[0,Q,-1,Bg],R],W,Cg,W,[0,[1,2],W,Ag,W,[0,T]]];var Kg=[0,Ne,vf,Ne,uf,Ne,wf];function Lg(a){this.j=F(a,4)}p(Lg,I);var Mg=[-4,{},V,Jg,Bg,Kg];function Ng(a){this.j=F(a,3)}p(Ng,I);var Og=xf([-3,{},V,ug,Mg]);function Pg(a){a=a===void 0?new AudioContext({sampleRate:24E3}):a;this.h=!1;this.o=[];this.S={};this.P={};this.C={};this.R={};this.B={};this.Y=new TextEncoder;this.V="";this.H=null;this.M=0;this.N=[];this.G=this.u=this.D=this.l=!1;this.v=[];this.O=[];this.A=[];this.i=a;this.F=this.i.createGain()}aa=Pg.prototype;
aa.init=function(a){var b=this;return t(function(c){switch(c.g){case 1:if(b.h)return c.return();b.h=!0;b.extensionId=a;return r(c,loadWasmTtsBindings(),2);case 2:return b.g=c.h,r(c,Qg(b),3);case 3:return r(c,Rg(b),4);case 4:return c.return(Sg(b))}})};aa.onLanguageStatusRequest=function(a){var b=this,c,d;return t(function(e){return e.g==1?(b.h?(e.g=2,e=void 0):e=r(e,b.init(b.extensionId),2),e):e.g!=4?(c="offscreenLanguageStatusResponse",d=a,r(e,Tg(b,a),4)):e.return({type:c,lang:d,status:e.h})})};
aa.onInstallLanguageRequest=function(a){var b=this,c,d;return t(function(e){return e.g==1?(b.h?(e.g=2,e=void 0):e=r(e,b.init(b.extensionId),2),e):e.g!=4?(c="offscreenLanguageStatusResponse",d=a,r(e,Ug(b,a),4)):e.return({type:c,lang:d,status:e.h})})};
aa.onUninstallLanguageRequest=function(a){var b=this,c;return t(function(d){if(d.g==1)return b.h?(d.g=2,d=void 0):d=r(d,b.init(b.extensionId),2),d;if(d.g!=4)return r(d,Vg(b,a),4);(c=d.h)&&Wg(b);return d.return({type:"offscreenLanguageStatusResponse",lang:a,status:"notInstalled"})})};
function Vg(a,b){var c,d,e,f,g,h;return t(function(k){switch(k.g){case 1:c=Xg(a,b),d=!1,e=q(c),f=e.next();case 2:if(f.done){k.g=4;break}g=f.value;Yg(a,g);if(!g.remote||g.unloaded){k.g=3;break}h="/voices/"+g.fileId;k.i=5;return r(k,Zg(a,h),7);case 7:d=!0;qa(k,3);break;case 5:ra(k);case 3:f=e.next();k.g=2;break;case 4:return k.return(d)}})}
aa.onStop=function(a){var b=this,c;return t(function(d){if(!b.h)return d.return();$g(b);b.l=!1;b.D=!1;b.u=a;b.m&&(c={command:"clearBuffers"},b.m.port.postMessage(c),b.m.disconnect());for(ah(b);b.O.length>0;)window.clearTimeout(b.O.pop());b.v=[];b.N.length=0;b.H=null;b.M=0;d.g=0})};aa.onPause=function(){var a=this;return t(function(b){if(b.g==1){if(!a.h)return b.return();ah(a);a.u=!0;return r(b,a.i.suspend(),2)}a.l=!1;b.g=0})};
aa.onResume=function(){var a=this;return t(function(b){if(b.g==1){if(!a.h||a.l)return b.return();a.u=!1;return a.D?r(b,a.i.resume(),2):(a.A.length===0&&bh(a),b.return(ch(a)))}a.l=!0;dh(a);b.g=0})};
aa.onSpeak=function(a,b){var c=this,d,e,f,g,h;return t(function(k){switch(k.g){case 1:return c.u=!1,r(k,c.init(c.extensionId),2);case 2:if(!c.g)throw Error("WASM module not initialized.");return b.voiceName?r(k,c.onStop(!1),3):k.return();case 3:c.utterance=a;d=b.voiceName;if(c.V===d){k.g=4;break}k.i=5;return r(k,eh(c,d,!1),7);case 7:e=c.C[d];if(!e)throw Error("Invalid voice name: "+b.voiceName);f=["/voices",e].join("/");g=[f,"pipeline.pb"].join("/");if(c.g){var m=fh(c,g);var n=fh(c,f),w=c.g._GoogleTtsInit(m,
n);c.g._free(n);c.g._free(m);m=w===1}else m=!1;if(!m)throw Error("Failed to initialize pipeline "+g);qa(k,4);break;case 5:return ra(k),k.return(Promise.reject(Error("Voice is not available")));case 4:c.V=d;var x=b.lang;c.extensionId&&x&&chrome.runtime.sendMessage(c.extensionId,{type:"languageUsed",language:x});try{if(x=d,c.g&&a.length){var z=new Eg,G=new Dg;var C=Od(G,2,pd(a));var S=de(z,[C]);var mh=new xg,Mb=b.rate;var nh=Td(mh,1,yg,bd(!Mb||Mb<.1||Mb>10?1:Mb));var Of=b.pitch;m=Od(nh,6,bd(Of?Math.pow(2,
(Of-1)*20/12):1));b.volume!==void 0&&b.volume>=0&&(c.F.gain.value=Math.min(Math.max(b.volume,0),1));n=new Lg;w=new Fg;z=S;z=be(z);Td(w,2,Gg,z);z&&!Oc(z)&&Ld(w.j);var oh=de(n,[w]);var ph=new zg;var qh=ce(ph,3,m);var rh=ce(oh,2,qh);var sh=new Ng;var th=ce(sh,2,rh);var dd=Array.from(new Uint8Array(Og(th))),uh=c.R[x],vh=new Ef;var wh=Od(vh,1,pd(uh));var ed=wg(wh),fd=c.g._malloc(dd.length);c.g.HEAPU8.set(dd,fd);var gd=c.g._malloc(ed.length);c.g.HEAPU8.set(ed,gd);var xh=c.g._GoogleTtsInitBuffered(fd,gd,
dd.length,ed.length);c.g._free(fd);c.g._free(gd);if(!xh)throw Error("Failed to initialize buffered synthesis.");bh(c)}}catch(Pf){return h=Pf instanceof Error?Pf.message:"",k.return(Promise.reject(Error("Synthesis failed with "+h)))}k.g=0}})};
function Sg(a){return a.i.audioWorklet.addModule("../streaming_worklet_processor.js").then(function(){a.m=new AudioWorkletNode(a.i,"streaming-worklet-processor");a.m.port.onmessage=function(b){a.utterance&&!a.G&&b.data.type==="empty"&&(gh(a,{type:"end",charIndex:a.utterance.length}),a.onStop(!1))};a.F.connect(a.i.destination)})}function fh(a,b){b=a.Y.encode(b+"\x00");var c=a.g._malloc(b.length);a.g.HEAPU8.set(b,c);return c}
function bh(a){var b=setTimeout(function(){a.G=!0;var c=a.g,d=c._GoogleTtsReadBuffered();if(d===-1)gh(a,{type:"error"}),$g(a);else{for(var e=c._GoogleTtsGetTimepointsCount(),f=0;f<e;f++)hh(a,{audioDeltaMillis:c._GoogleTtsGetTimepointsTimeInSecsAtIndex(f)*1E3,charIndex:Number(c._GoogleTtsGetTimepointsCharIndexAtIndex(f)),length:Number(c._GoogleTtsGetTimepointsCharLengthAtIndex(f))});f=c._GoogleTtsGetEventBufferPtr();e=c._GoogleTtsGetEventBufferLen();c=new Uint8Array(c.HEAPU8.buffer,f,e);c=vg(c.slice(0,
e));d=d===0;e=c.j;Zd(e,e[D]|0)!==void 0?ih(a,c,d):jh(a,null);d?$g(a):bh(a)}},0);a.A.push(b)}function $g(a){a.G=!1;a.g._GoogleTtsFinalizeBuffered()}function ah(a){for(;a.A.length>0;)window.clearTimeout(a.A.pop())}function hh(a,b){var c=b.audioDeltaMillis,d=b.charIndex,e=b.length;d<0||c<=0||(a.l?c<-100||(c<2?gh(a,{type:"word",charIndex:d,length:e}):(c=window.setTimeout(function(){a.l?gh(a,{type:"word",charIndex:d,length:e}):a.v.push(b)},c),a.O.push(c))):a.v.push(b))}
function dh(a){var b=a.v;a.v=[];b=q(b);for(var c=b.next();!c.done;c=b.next())hh(a,c.value)}function ih(a,b,c){if(Df(ae(b))===24E3){var d;b=(d=Cf(ae(b)))==null?void 0:new Uint8Array(Jb(d)||0);d=new Uint8Array(b);d=new Int16Array(d.buffer);d=Float32Array.from(d,function(e){return e/32768});kh(a,d,c)}}
function kh(a,b,c){for(var d=a.H,e=a.M,f=0,g=b.length;f<g;){var h=Math.min(128-e,g-f);d||(d=new Float32Array(128));d.set(b.subarray(f,f+h),e);f+=h;e+=h;e===128&&(jh(a,d),e=0,d=null)}e!==0&&(c?jh(a,d):(a.H=d,a.M=e))}function jh(a,b){b&&a.N.push(b);if(a.m)for(;b=a.N.shift();)a.m.port.postMessage({command:"addBuffer",buffer:b}),a.D||a.u||ch(a)}function ch(a){return t(function(b){if(b.g==1)return a.m.connect(a.F),r(b,a.i.resume(),2);a.l=!0;a.D=!0;gh(a,{type:"start",charIndex:0});dh(a);b.g=0})}
function Tg(a,b){return t(function(c){return c.return(lh(a,b,!1))})}function Ug(a,b){return t(function(c){return c.return(lh(a,b,!0))})}function lh(a,b,c){var d,e,f;return t(function(g){switch(g.g){case 1:return d=Xg(a,b),e=d.map(function(h){return eh(a,h.speakers[0].name,c)}),g.i=2,r(g,Promise.all(e),4);case 4:f="installed";c&&Wg(a);qa(g,3);break;case 2:ra(g),f=c?"failed":"notInstalled";case 3:return g.return(f)}})}
function Xg(a,b){var c=b.toLowerCase();return c.includes("-")?a.o.filter(function(d){var e;return((e=d.language)==null?void 0:e.toLowerCase())===c}):a.o.filter(function(d){var e;return((e=d.language)==null?void 0:e.split("-")[0])===c})}
function yh(a,b,c){var d,e,f,g,h,k,m,n,w,x;return t(function(z){if(!a.B[b])return z.return(Promise.resolve());d=a.B[b];f=q(Object.entries(a.P));for(g=f.next();!g.done;g=f.next())if(h=g.value,k=q(h),m=k.next().value,n=k.next().value,w=m,x=n,d===x){e=w;break}return e?z.return(eh(a,e,c)):z.return(Promise.reject(Error("No multivoice found for: "+b)))})}
function eh(a,b,c){var d,e,f,g,h,k;return t(function(m){switch(m.g){case 1:if(!a.g)return m.return(Promise.reject(Error("WASM module not initialized.")));m.i=2;return r(m,yh(a,b,c),4);case 4:qa(m,3);break;case 2:return d=ra(m),m.return(Promise.reject(Error(""+d)));case 3:e=a.C[b];if(!e)return m.return(Promise.reject(Error("Invalid voice name: "+b)));f=["/voices",e].join("/");g=[f,"pipeline.pb"].join("/");try{if(h=a.g.FS.stat(g))return m.return(Promise.resolve())}catch(n){}k=a.S[b];return c||k.indexOf("http")!==
0?m.return(fetch(k).then(function(n){return n.ok?n.arrayBuffer():Promise.reject(Error("Failed to fetch voice from url: "+k))}).then(function(n){if(!n)return Promise.reject(Error("Failed to fetch voice from url: "+k));if(!zh(a,e,n))return Promise.reject(Error("Failed to validate voice data: "+e));try{a.g.FS.stat(f)}catch(G){a.g.FS.mkdir(f)}a.g.FS.stat(f);var w=fh(a,f),x=new Uint8Array(n),z=a.g._malloc(x.length);a.g.HEAPU8.set(x,z);n=a.g._GoogleTtsInstallVoice(w,z,n.byteLength);a.g._free(w);a.g._free(z);
return n!==1?Promise.reject(Error("Failed to install voice.")):new Promise(function(G,C){a.g.FS.syncfs(!1,function(S){S?C(S):G()})})})):m.return(Promise.reject(Error("Not downloading remote voice because caller did not request it.")))}})}function gh(a,b){a.extensionId&&chrome.runtime.sendMessage(a.extensionId,{type:"offscreenTtsEventResponse",event:b})}
function Qg(a){var b,c;return t(function(d){if(d.g==1){if((b=a.g)==null||!b.FS)throw Error("WASM FS not ready for IDBFS setup.");try{a.g.FS.stat("/voices")}catch(e){a.g.FS.mkdir("/voices")}d.i=2;return r(d,new Promise(function(e,f){a.g.FS.mount(a.g.IDBFS,{},"/voices");a.g.FS.syncfs(!0,function(g){g?f(g):e()})}),4)}if(d.g!=2)return qa(d,0);c=ra(d);throw c;})}
function Rg(a){var b,c,d;return t(function(e){switch(e.g){case 1:return e.i=2,r(e,fetch("voices.json"),4);case 4:b=e.h;if(!b.ok)throw Error("Failed to fetch voices.json: "+b.statusText+" ("+b.status+")");return r(e,b.json(),5);case 5:c=e.h;a.o=c;Wg(a);qa(e,0);break;case 2:throw d=ra(e),d;}})}
function Wg(a){a.S={};a.P={};a.C={};a.R={};a.B={};for(var b={},c=q(a.o),d=c.next();!d.done;d=c.next()){d=d.value;for(var e=q(d.speakers),f=e.next();!f.done;f=e.next()){f=f.value;a.P[f.name]=d.id;a.C[f.name]=d.fileId;a.R[f.name]=f.speaker;d.dependentVoiceId&&(a.B[f.name]=d.dependentVoiceId);Yg(a,d);a.S[f.name]=d.remote&&d.unloaded?d.url:"/"+d.id+".zvoice";var g=d.id.split("-");if(g.length<2)throw Error("Unexpected voice id format: "+d.id);g=g[0]+"-"+g[1].toUpperCase();d.language=g;d.remote&&d.unloaded||
(b[g]||(b[g]=[]),b[g].push(f.name))}}a.extensionId&&chrome.runtime.sendMessage(a.extensionId,{type:"offscreenVoicesResponse",voices:b})}function Yg(a,b){try{a.g.FS.stat(["/voices",b.fileId].join("/")),b.unloaded=!1}catch(c){b.unloaded=!0}}
function Zg(a,b){if(a.g)try{for(var c=a.g.FS.readdir(b),d=q(c),e=d.next();!e.done;e=d.next()){var f=e.value;f!=="."&&f!==".."&&a.g.FS.unlink(b+"/"+f)}a.g.FS.rmdir(b);return new Promise(function(g,h){a.g.FS.syncfs(!1,function(k){k?h(k):g()})})}catch(g){return Promise.resolve()}}function zh(a,b,c){var d,e;return t(function(f){if(f.g==1)return r(f,Ah(c),2);d=f.h;e=a.o.find(function(g){return g.fileId===b});return f.return(e!==void 0&&e.sha256Checksum===d&&e.compressedSize===c.byteLength)})}
function Ah(a){var b,c,d,e;return t(function(f){if(f.g==1)return crypto&&crypto.subtle?r(f,crypto.subtle.digest("SHA-256",a),2):f.return("");b=f.h;c="";for(d=0;d<b.byteLength;d++)e=(new Uint8Array(b))[d],c+=Number(e>>4).toString(16),c+=Number(e&15).toString(16);return f.return(c)})}ea.Object.defineProperties(Pg.prototype,{voices:{configurable:!0,enumerable:!0,get:function(){return this.o}}});var Bh=new Pg,Ch=null;
chrome.runtime.onMessage.addListener(function(a,b,c){Ch||(Ch=Bh.init(b.id));Ch.then(function(){switch(a.type){case "init":Bh.init(b.id);c({result:"Initialized"});break;case "getLanguageStatus":Bh.onLanguageStatusRequest(a.lang).then(c);break;case "installLanguage":Bh.onInstallLanguageRequest(a.lang).then(c);break;case "uninstallLanguage":Bh.onUninstallLanguageRequest(a.lang).then(c);break;case "removeUnusedLanguage":Vg(Bh,a.lang).then(function(){c({result:"Removed "+a.lang})});break;case "speak":Bh.onSpeak(a.utterance,
a.options);c({result:"Start speaking"});break;case "stop":Bh.onStop(!0);c({result:"Stopped speech"});break;case "pause":Bh.onPause();c({result:"Paused speech"});break;case "resume":Bh.onResume(),c({result:"Resumed speech"})}});return!0});
